version: 2.1

jobs:
  unit_tests:
    macos:
      xcode: 13.4.1
    steps:
      - run:
          name: bundler install from Gemfile
          working_directory: CodeCoverageTutorial
          command: bundle install
      - run:
          name: Update fastlane
          command: bundle update fastlane
      - run:
          name: Run tests
          command: bundle exec fastlane unit_testing --verbose
      - run:
          name: Run code coverage report tool
          command: bundle exec danger --verbose

workflows:
  test:
    jobs:
      - unit_tests
